// Auth
export const START_AUTH_ACTION = 'START_AUTH_ACTION';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// Activities
export const START_ACTIVITIES_ACTION = 'START_ACTIVITIES_ACTION';
export const FAILED_ACTIVITIES_ACTION = 'FAILED_ACTIVITIES_ACTION';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const GET_ALL_ACTIVITIES_SUCCESS = 'GET_ALL_ACTIVITIES_SUCCESS';
export const SELECT_ACTIVITY = 'SELECT_ACTIVITY';
export const SEARCH_ACTIVITIES = 'SEARCH_ACTIVITIES';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';

// Agents
export const START_AGENTS_ACTION = 'START_AGENTS_ACTION';
export const FAILED_AGENTS_ACTION = 'FAILED_AGENTS_ACTION';
export const CREATE_AGENT = 'CREATE_AGENT';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const GET_AGENTS = 'GET_AGENTS';
export const GET_AGENTS_SUCCESS = 'GET_AGENTS_SUCCESS';
export const GET_AGENT = 'GET_AGENT';
export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS';
export const SEARCH_AGENTS = 'SEARCH_AGENTS';
export const SELECT_AGENT = 'SELECT_AGENT';
export const UPDATE_AGENT = 'UPDATE_AGENT';
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS';
export const DELETE_AGENT = 'DELETE_AGENT';
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS';

// Municipalities
export const START_MUNICIPALITIES_ACTION = 'START_MUNICIPALITIES_ACTION';
export const FAILED_MUNICIPALITIES_ACTION = 'FAILED_MUNICIPALITIES_ACTION';
export const GET_MUNICIPALITIES = 'GET_MUNICIPALITIES';
export const GET_MUNICIPALITIES_SUCCESS = 'GET_MUNICIPALITIES_SUCCESS';
export const SEARCH_MUNICIPALITIES = 'SEARCH_MUNICIPALITIES';

// Sectors
export const START_SECTORS_ACTION = 'START_SECTORS_ACTION';
export const FAILED_SECTORS_ACTION = 'FAILED_SECTORS_ACTION';
export const CREATE_SECTOR = 'CREATE_SECTOR';
export const CREATE_SECTOR_SUCCESS = 'CREATE_SECTOR_SUCCESS';
export const GET_SECTORS = 'GET_SECTORS';
export const GET_SECTORS_SUCCESS = 'GET_SECTORS_SUCCESS';
export const GET_ALL_SECTORS = 'GET_ALL_SECTORS';
export const GET_ALL_SECTORS_SUCCESS = 'GET_ALL_SECTORS_SUCCESS';
export const SELECT_SECTOR = 'SELECT_SECTOR';
export const SEARCH_SECTORS = 'SEARCH_SECTORS';
export const UPDATE_SECTOR = 'UPDATE_SECTOR';
export const UPDATE_SECTOR_SUCCESS = 'UPDATE_SECTOR_SUCCESS';
export const DELETE_SECTOR = 'DELETE_SECTOR';
export const DELETE_SECTOR_SUCCESS = 'DELETE_SECTOR_SUCCESS';

export const START_VALUE_CHAINS_ACTION = 'START_VALUE_CHAINS_ACTION';
export const FAILED_VALUE_CHAINS_ACTION = 'FAILED_VALUE_CHAINS_ACTION';
export const CREATE_VALUE_CHAIN = 'CREATE_VALUE_CHAIN';
export const CREATE_VALUE_CHAIN_SUCCESS = 'CREATE_VALUE_CHAIN_SUCCESS';
export const GET_VALUE_CHAINS = 'GET_VALUE_CHAINS';
export const GET_VALUE_CHAINS_SUCCESS = 'GET_VALUE_CHAINS_SUCCESS';
export const SELECT_VALUE_CHAIN = 'SELECT_VALUE_CHAIN';
export const SEARCH_VALUE_CHAINS = 'SEARCH_VALUE_CHAINS';
export const UPDATE_VALUE_CHAIN = 'UPDATE_VALUE_CHAIN';
export const UPDATE_VALUE_CHAIN_SUCCESS = 'UPDATE_VALUE_CHAIN_SUCCESS';
export const DELETE_VALUE_CHAIN = 'DELETE_VALUE_CHAIN';
export const DELETE_VALUE_CHAIN_SUCCESS = 'DELETE_VALUE_CHAIN_SUCCESS';

export const START_LEGAL_FORMS_ACTION = 'START_LEGAL_FORMS_ACTION';
export const FAILED_LEGAL_FORMS_ACTION = 'FAILED_LEGAL_FORMS_ACTION';
export const CREATE_LEGAL_FORM = 'CREATE_LEGAL_FORM';
export const CREATE_LEGAL_FORM_SUCCESS = 'CREATE_LEGAL_FORM_SUCCESS';
export const GET_LEGAL_FORMS = 'GET_LEGAL_FORMS';
export const GET_LEGAL_FORMS_SUCCESS = 'GET_LEGAL_FORMS_SUCCESS';
export const SELECT_LEGAL_FORM = 'SELECT_LEGAL_FORM';
export const SEARCH_LEGAL_FORMS = 'SEARCH_LEGAL_FORMS';
export const UPDATE_LEGAL_FORM = 'UPDATE_LEGAL_FORM';
export const UPDATE_LEGAL_FORM_SUCCESS = 'UPDATE_LEGAL_FORM_SUCCESS';
export const DELETE_LEGAL_FORM = 'DELETE_LEGAL_FORM';
export const DELETE_LEGAL_FORM_SUCCESS = 'DELETE_LEGAL_FORM_SUCCESS';

export const START_SCOPES_ACTION = 'START_SCOPES_ACTION';
export const FAILED_SCOPES_ACTION = 'FAILED_SCOPES_ACTION';
export const CREATE_SCOPE = 'CREATE_SCOPE';
export const CREATE_SCOPE_SUCCESS = 'CREATE_SCOPE_SUCCESS';
export const GET_SCOPES = 'GET_SCOPES';
export const GET_SCOPES_SUCCESS = 'GET_SCOPES_SUCCESS';
export const SELECT_SCOPE = 'SELECT_SCOPE';
export const SEARCH_SCOPES = 'SEARCH_SCOPES';
export const UPDATE_SCOPE = 'UPDATE_SCOPE';
export const UPDATE_SCOPE_SUCCESS = 'UPDATE_SCOPE_SUCCESS';
export const DELETE_SCOPE = 'DELETE_SCOPE';
export const DELETE_SCOPE_SUCCESS = 'DELETE_SCOPE_SUCCESS';

export const START_SUB_SECTORS_ACTION = 'START_SUB_SECTORS_ACTION';
export const FAILED_SUB_SECTORS_ACTION = 'FAILED_SUB_SECTORS_ACTION';
export const CREATE_SUB_SECTOR = 'CREATE_SUB_SECTOR';
export const CREATE_SUB_SECTOR_SUCCESS = 'CREATE_SUB_SECTOR_SUCCESS';
export const GET_SUB_SECTORS = 'GET_SUB_SECTORS';
export const GET_SUB_SECTORS_SUCCESS = 'GET_SUB_SECTORS_SUCCESS';
export const GET_ALL_SUB_SECTORS = 'GET_ALL_SUB_SECTORS';
export const GET_ALL_SUB_SECTORS_SUCCESS = 'GET_ALL_SUB_SECTORS_SUCCESS';
export const SELECT_SUB_SECTOR = 'SELECT_SUB_SECTOR';
export const SEARCH_SUB_SECTORS = 'SEARCH_SUB_SECTORS';
export const UPDATE_SUB_SECTOR = 'UPDATE_SUB_SECTOR';
export const UPDATE_SUB_SECTOR_SUCCESS = 'UPDATE_SUB_SECTOR_SUCCESS';
export const DELETE_SUB_SECTOR = 'DELETE_SUB_SECTOR';
export const DELETE_SUB_SECTOR_SUCCESS = 'DELETE_SUB_SECTOR_SUCCESS';

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
